### ISSUE TITLE
The sample won't pass as cowsay is not in the system path

### ISSUE THREAD

**Issue by mfunaki** [CircleCI-Public/cimg-base#154]
The revised version of config.yml is something like this:
```
jobs:
  build:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: /usr/games/cowsay Continuous Integration Rocks!
```
