### ISSUE TITLE
Basic Checkout of build fails on 22.04, works on 20.04

### ISSUE THREAD

**Issue by smanleyjr** [CircleCI-Public/cimg-base#175]
I did a basic run checkout step using cimg/base:2022.06-22.04 and cimg/base:2022.06-20.04....
Why is 22.04 failing? but 20.04 works? 

### Error Seen when failing
> Using SSH Config Dir '/home/circleci/.ssh'
> git version 2.36.1
> Cloning git repository
> Cloning into '.'...
> error: cannot create async thread: Operation not permitted
> fatal: fetch-pack: unable to fork off sideband demultiplexer
> 
> exit status 128

### Simple config 

```
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  build:
    working_directory: /home/circleci/project
    docker:
     # - image: cimg/node:12.20.2
      - image: cimg/base:2022.06-22.04
     # - image: cimg/base:2022.06-20.04

    steps:
      - checkout
      - run: echo $(ls -a) 
      
workflows:
  version: 2
  test:
    jobs:
        - build:
            context: 
              - smanley1-XXX17-Sndbx
```
